# make_timeblock_table.R
# ---------------------------------------------------------------------------
# LaTeX table for the time-block forecast paired tests, Brier vs CRPS side by
# side, for the two AR(2) contrasts. Shows that the AR(2) forecasting gain is
# invisible on q95 Brier (single-threshold, high variance) but marginally
# significant on CRPS (whole predictive distribution).
#
# Reads (from block1_positive_control/output/tables/):
#   blk1_paired_ci.csv        (Brier;  timeblock_paired_export.R)
#   blk1_paired_ci_crps.csv   (CRPS;   timeblock_crps_export.R)   [optional]
# Writes: timeblock_table_body.tex
# ---------------------------------------------------------------------------

.this <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "."
})
tdir <- normalizePath(file.path(.this,
  "../../../code/analysis/time_block_forecast/block1_positive_control/output/tables"),
  winslash = "/", mustWork = FALSE)

brier <- read.csv(file.path(tdir, "blk1_paired_ci.csv"), stringsAsFactors = FALSE)
crps_f <- file.path(tdir, "blk1_paired_ci_crps.csv")
crps <- if (file.exists(crps_f)) read.csv(crps_f, stringsAsFactors = FALSE) else NULL
if (is.null(crps)) message("NOTE: CRPS csv not found yet; emitting Brier-only columns.")

# cell in given scale (Brier x1e3, CRPS x1) with CI and Wilcoxon star
# (Brier csv carries a two-sided Wilcoxon p, CRPS csv a one-sided one)
cellf <- function(df, st, ld, con, scale) {
  r <- df[df$setting == st & df$leads == ld & df$contrast == con, ]
  if (nrow(r) == 0) return("\\multicolumn{1}{c}{--}")
  wp <- if (!is.null(r$wilcox_p_2sided)) r$wilcox_p_2sided else r$wilcox_p_1sided
  star <- if (isTRUE(wp < 0.05)) "^{*}" else ""
  sprintf("$%+.2f%s$ {\\scriptsize $[%+.2f,%+.2f]$}",
          scale * r$Delta, star, scale * r$CI_lo, scale * r$CI_hi)
}

settings <- c(5, 7); sdesc <- c(`5` = "near-unit-root", `7` = "ARFIMA $d{=}0.45$")
winds <- c("1-5", "1-15")
cons <- list(c("AR(2) - iid", "AR(2) $-$ iid (does memory help?)"),
             c("AR(2) - AR(1)", "AR(2) $-$ AR(1) (value of 2nd lag)"))

lines <- c(
  "% Auto-generated by make_timeblock_table.R -- do not edit by hand.",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Time-block forecast arm: paired differences over the $10$ clean",
  "data sets, temporal model minus reference (negative favours the temporal",
  "model), with $95\\%$ paired-$t$ CIs. Brier at $q_{95}$ in units of $10^{-3}$;",
  "CRPS in native units. Stars mark a Wilcoxon $p<0.05$ (two-sided for Brier;",
  "one-sided for CRPS, H$_1$: temporal model better). The AR(2) gain is",
  "invisible on single-threshold",
  "Brier but reaches (marginal) significance on CRPS, whose whole-distribution",
  "scoring carries far more information per forecast.}",
  "\\label{tab:timeblock-paired}",
  "\\small",
  "\\begin{tabular}{@{}ll cc@{}}",
  "\\toprule",
  "Design & Leads & Brier$_{q95}\\times10^{3}$ [CI] & CRPS [CI] \\\\",
  "\\midrule"
)
for (cc in cons) {
  con <- cc[1]
  lines <- c(lines, sprintf("\\multicolumn{4}{@{}l}{\\emph{%s}}\\\\", cc[2]))
  for (st in settings) {
    first <- TRUE
    for (ld in winds) {
      bcell <- cellf(brier, st, ld, con, 1e3)
      ccell <- if (!is.null(crps)) cellf(crps, st, ld, con, 1) else "\\multicolumn{1}{c}{--}"
      lab <- if (first) sdesc[as.character(st)] else ""
      first <- FALSE
      lines <- c(lines, sprintf("%s & %s & %s & %s \\\\", lab, ld, bcell, ccell))
    }
  }
  lines <- c(lines, "\\addlinespace")
}
lines <- c(lines[-length(lines)], "\\bottomrule", "\\end{tabular}", "\\end{table}")

out <- file.path(.this, "timeblock_table_body.tex")
writeLines(lines, out); cat("Written:", out, "\n")
cat(readLines(out), sep = "\n")
