# make_block_table.R
# ---------------------------------------------------------------------------
# Spatial block-bootstrap sensitivity for the ozone AR(2) vs AR(1) pair: does
# the significant plain-CRPS "AR(2) worse" survive once between-site spatial
# correlation is respected (resampling geographic blocks, not single sites)?
#
# Reads block_bootstrap_sensitivity_{200-200,300-100}.csv (US-all-auto tables).
# Writes: block_table_body.tex
# ---------------------------------------------------------------------------

.this <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "."
})
td <- normalizePath(file.path(.this,
  "../../../code/analysis/ozone/US-all-auto/output/us-all-auto/tables"),
  winslash = "/", mustWork = FALSE)
rd <- function(f) { p <- file.path(td, f); if (file.exists(p)) read.csv(p, stringsAsFactors = FALSE) else NULL }

# p-cell: value, starred if CI excludes 0
pc <- function(df, sc, scheme) {
  r <- df[df$score == sc & df$scheme == scheme, ]
  if (nrow(r) == 0) return("--")
  star <- if (r$CI_lo[1] > 0 || r$CI_hi[1] < 0) "^{*}" else ""
  sprintf("$%.3f%s$", r$boot_p[1], star)
}
dcell <- function(df, sc) {   # point Delta (scheme-invariant) with site CI
  r <- df[df$score == sc & df$scheme == "site", ]
  if (nrow(r) == 0) return("--")
  formatC(r$Delta[1], format = "fg", digits = 2, flag = "+")
}
sclab <- c(brier = "Brier $q_{.95}$", twcrps = "twCRPS (tail)", crps = "plain CRPS")

L <- c(
  "% Auto-generated by make_block_table.R -- do not edit by hand.",
  "\\begin{table}[htbp]", "\\centering",
  "\\caption{Spatial block-bootstrap sensitivity, ozone AR(2) vs.\\ AR(1). $p$ is",
  "the two-sided bootstrap $p$ for $\\Delta=\\mathrm{CRPS}_{AR(2)}-\\mathrm{CRPS}_{AR(1)}$;",
  "a star marks a $95\\%$ CI excluding $0$. Columns move from resampling single",
  "sites (assumes spatial independence) to resampling geographic blocks (keeps",
  "spatially-correlated neighbours together; coarser blocks absorb longer-range",
  "correlation). The two tail scores stay null throughout; the plain-CRPS",
  "``AR(2) worse'' is significant only under the (anticonservative) site",
  "resampling and dissolves as soon as blocks respect spatial dependence.}",
  "\\label{tab:block-sensitivity}", "\\small",
  "\\begin{tabular}{@{}ll c cccc@{}}", "\\toprule",
  "Split & Score & $\\Delta$ & site & block (12) & block ($\\approx$20) & block ($\\approx$32) \\\\",
  "\\midrule")

for (split in c("200-200", "300-100")) {
  df <- rd(sprintf("block_bootstrap_sensitivity_%s.csv", split))
  if (is.null(df)) next
  df <- df[df$pair == "AR(2) vs AR(1)", ]
  L <- c(L, sprintf("\\multicolumn{7}{@{}l}{\\emph{%s split}}\\\\", sub("-", "/", split)))
  for (sc in c("brier", "twcrps", "crps")) {
    L <- c(L, sprintf("& %s & $%s$ & %s & %s & %s & %s \\\\",
      sclab[sc], dcell(df, sc), pc(df, sc, "site"),
      pc(df, sc, "block_coarse"), pc(df, sc, "block_med"), pc(df, sc, "block_fine")))
  }
  L <- c(L, "\\addlinespace")
}
L <- c(L[-length(L)], "\\bottomrule", "\\end{tabular}", "\\end{table}")
out <- file.path(.this, "block_table_body.tex")
writeLines(L, out); cat("Written:", out, "\n"); cat(readLines(out), sep = "\n")
