# make_brier_ci_table.R
# ---------------------------------------------------------------------------
# Turn the site-clustered bootstrap CSVs into a thesis-ready LaTeX table
# (paired Brier difference Delta = BS_ext - BS_matched-baseline, with a 95%
# site-clustered bootstrap CI, across exceedance levels and CV splits).
#
# Reads:
#   code/analysis/ozone/US-all-auto/output/us-all-auto/tables/
#       brier_bootstrap_pairs_200-200.csv
#       brier_bootstrap_pairs_300-100.csv
# Writes (next to this script):
#   brier_ci_table_body.tex   -- the { table } float, \input-able into the thesis
# ---------------------------------------------------------------------------

.this <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "."
})

tab_dir <- normalizePath(file.path(.this,
  "../../../code/analysis/ozone/US-all-auto/output/us-all-auto/tables"),
  winslash = "/", mustWork = FALSE)

read_split <- function(tag) {
  f <- file.path(tab_dir, sprintf("brier_bootstrap_pairs_%s.csv", tag))
  if (!file.exists(f)) return(NULL)
  d <- read.csv(f, stringsAsFactors = FALSE)
  d$split <- tag
  d
}
d <- do.call(rbind, Filter(Negate(is.null), list(read_split("200-200"), read_split("300-100"))))
stopifnot(!is.null(d))

# short label for the pair (family only)
d$fam <- ifelse(grepl("^AR\\(2\\)", d$pair), "AR(2) vs.\\ AR(1)",
         ifelse(grepl("^MRTS",      d$pair), "MRTS vs.\\ none", d$pair))

# format one cell: Delta and CI in units of 1e-3, star if CI excludes 0
cell <- function(delta, lo, hi) {
  if (is.na(delta)) return("\\multicolumn{1}{c}{--}")
  star <- if (lo > 0 || hi < 0) "^{*}" else ""
  sprintf("$%+.2f%s$ {\\scriptsize $[%+.2f,\\,%+.2f]$}",
          1e3 * delta, star, 1e3 * lo, 1e3 * hi)
}

levels_u <- sort(unique(d$level))
fams <- unique(d$fam)
splits <- c("200-200", "300-100")

lines <- c(
  "% Auto-generated by make_brier_ci_table.R -- do not edit by hand.",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Paired held-out Brier differences for each extension against its",
  "matched baseline, $\\Delta = \\mathrm{BS}_{\\text{ext}} - \\mathrm{BS}_{\\text{base}}$",
  "(negative favours the extension), in units of $10^{-3}$, with $95\\%$",
  "site-clustered bootstrap confidence intervals in brackets ($B=2000$).",
  "AR(2) vs.\\ AR(1): skew-$t$, $K{=}7$, $T{=}50$; MRTS vs.\\ none: skew-$t$,",
  "$K{=}1$, $T{=}0$. $n_{\\mathrm{exc}}$ is the number of exceedance events",
  "behind the score. Every interval covers $0$ except the starred one",
  "($q{=}0.995$, $200/200$), which sits at the sparsest level and does not",
  "survive multiplicity across the $15$ comparisons.}",
  "\\label{tab:ozone-brier-ci}",
  "\\small",
  "\\begin{tabular}{@{}ll r@{\\ }l r@{\\ }l@{}}",
  "\\toprule",
  "& & \\multicolumn{2}{c}{$200/200$ split} & \\multicolumn{2}{c}{$300/100$ split} \\\\",
  "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
  "Comparison & $L$ quantile & $\\Delta\\times10^{3}$ [95\\% CI] & $n_{\\mathrm{exc}}$ & $\\Delta\\times10^{3}$ [95\\% CI] & $n_{\\mathrm{exc}}$ \\\\",
  "\\midrule"
)

for (fam in fams) {
  first <- TRUE
  for (lv in levels_u) {
    getrow <- function(tag) d[d$fam == fam & d$level == lv & d$split == tag, ]
    r2 <- getrow("200-200"); r3 <- getrow("300-100")
    c2 <- if (nrow(r2)) cell(r2$Delta, r2$CI_lo, r2$CI_hi) else "\\multicolumn{1}{c}{--}"
    n2 <- if (nrow(r2)) as.character(r2$n_exceed)          else "--"
    c3 <- if (nrow(r3)) cell(r3$Delta, r3$CI_lo, r3$CI_hi) else "\\multicolumn{1}{c}{--}"
    n3 <- if (nrow(r3)) as.character(r3$n_exceed)          else "--"
    lab <- if (first) fam else ""
    first <- FALSE
    lines <- c(lines, sprintf("%s & $%.3f$ & %s & %s & %s & %s \\\\",
                              lab, lv, c2, n2, c3, n3))
  }
  lines <- c(lines, "\\addlinespace")
}
lines <- c(lines[-length(lines)],  # drop trailing addlinespace
           "\\bottomrule", "\\end{tabular}", "\\end{table}")

out <- file.path(.this, "brier_ci_table_body.tex")
writeLines(lines, out)
cat("Written:", out, "\n")
cat(readLines(out), sep = "\n")
