# make_ar2_sim_table.R
# ---------------------------------------------------------------------------
# LaTeX table for the AR(2) simulation spatial hold-out paired tests
# (thesis Figure 1, settings 9-12). Pivots the two core AR(2) contrasts
# side by side: AR(2) vs no-TS  and  AR(2) vs AR(1), across settings x levels.
#
# Reads:  code/analysis/simstudy/output/results/ar2_paired_tests.csv
# Writes: ar2_sim_table_body.tex  (\input-able table float)
# ---------------------------------------------------------------------------

.this <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "."
})
csv <- normalizePath(file.path(.this,
  "../../../code/analysis/simstudy/output/results/ar2_paired_tests.csv"),
  winslash = "/", mustWork = FALSE)
d <- read.csv(csv, stringsAsFactors = FALSE)

cell <- function(r) {
  if (nrow(r) == 0) return("\\multicolumn{1}{c}{--}")
  star <- if (r$CI_lo > 0 || r$CI_hi < 0) "^{*}" else ""
  sprintf("$%+.2f%s$ {\\scriptsize $[%+.2f,\\,%+.2f]$}",
          1e3 * r$Delta, star, 1e3 * r$CI_lo, 1e3 * r$CI_hi)
}
getr <- function(st, lv, con) d[d$setting == st & abs(d$level - lv) < 1e-6 &
                                  startsWith(trimws(d$contrast), con), ]

settings <- c(9, 10, 11, 12)
sdesc <- c(`9` = "K{=}1 strong", `10` = "K{=}1 weak", `11` = "K{=}5 strong", `12` = "K{=}5 weak")
levels_u <- sort(unique(d$level))

lines <- c(
  "% Auto-generated by make_ar2_sim_table.R -- do not edit by hand.",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{AR(2) simulation, spatial hold-out arm (settings 9--12): paired",
  "Brier differences over the $10$ data sets, $\\Delta=\\mathrm{BS}_A-\\mathrm{BS}_B$",
  "in units of $10^{-3}$ (negative favours the first-named model), with $95\\%$",
  "paired-$t$ confidence intervals. Two core contrasts: the temporal model",
  "against its non-temporal counterpart, and AR(2) against AR(1). Every",
  "interval covers $0$ except one starred cell (setting~11, $q{=}0.90$), which",
  "favours the \\emph{baseline}, is borderline ($p_W{=}0.05$), and does not",
  "survive multiplicity across the $36$ comparisons. This is the quantitative",
  "form of ``the temporal curves sit on top of their non-temporal counterparts.''}",
  "\\label{tab:ar2-sim-paired}",
  "\\small",
  "\\begin{tabular}{@{}ll cc@{}}",
  "\\toprule",
  "Setting & $L$ quantile & AR(2) $-$ no-TS & AR(2) $-$ AR(1) \\\\",
  "\\midrule"
)
for (st in settings) {
  first <- TRUE
  for (lv in levels_u) {
    a <- cell(getr(st, lv, "AR(2) vs no-TS")); b <- cell(getr(st, lv, "AR(2) vs AR(1)"))
    lab <- if (first) sprintf("%d (%s)", st, sdesc[as.character(st)]) else ""
    first <- FALSE
    lines <- c(lines, sprintf("%s & $%.2f$ & %s & %s \\\\", lab, lv, a, b))
  }
  lines <- c(lines, "\\addlinespace")
}
lines <- c(lines[-length(lines)], "\\bottomrule", "\\end{tabular}", "\\end{table}")

out <- file.path(.this, "ar2_sim_table_body.tex")
writeLines(lines, out); cat("Written:", out, "\n")
cat(readLines(out), sep = "\n")
