# make_bulk_tail_table.R
# ---------------------------------------------------------------------------
# Bulk-vs-tail across all three arms: for the AR(2) contrast, is each score's
# verdict a TAIL effect (Brier & twCRPS, tail-focused) or a BULK effect (plain
# CRPS, whole distribution)? Columns = three scores; rows = arm x contrast.
#
# Reads the paired-difference CSVs produced across the project:
#   ozone:      US-all-auto/output/us-all-auto/tables/{brier,twcrps,crps}_bootstrap_pairs_200-200.csv
#   sim:        simstudy/output/results/ar2_{paired_tests,twcrps_paired,crps_paired}.csv
#   time-block: block1_positive_control/output/tables/blk1_paired_ci{,_twcrps,_crps}.csv
# Writes: bulk_tail_table_body.tex
# ---------------------------------------------------------------------------

.this <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "."
})
root <- normalizePath(file.path(.this, "../../../code/analysis"), winslash = "/", mustWork = FALSE)
rd <- function(...) { f <- file.path(root, ...); if (file.exists(f)) read.csv(f, stringsAsFactors = FALSE) else NULL }

# a cell: verdict (by p<0.05) with p in small type; "--" if row missing.
# p-column name varies across CSVs (boot_p / wilcox_p_1sided / w_p); take the
# requested one, else fall back to whichever p-column exists.
cell <- function(r, pcol) {
  if (is.null(r) || nrow(r) == 0) return("\\multicolumn{1}{c}{--}")
  pcands <- c(pcol, "boot_p", "wilcox_p_1sided", "w_p")
  pcol2 <- pcands[pcands %in% names(r)][1]
  p <- r[[pcol2]][1]; De <- r$Delta[1]
  if (is.null(p) || is.na(p)) return("\\multicolumn{1}{c}{--}")
  v <- if (!isTRUE(p < 0.05)) "ns" else if (De < 0) "\\textbf{better}" else "\\textbf{worse}"
  sprintf("%s {\\scriptsize $p{=}%.3f$}", v, p)
}

# ---- gather rows: list(arm-label, contrast, brier-cell, twcrps-cell, crps-cell) ----
OZ <- "ozone/US-all-auto/output/us-all-auto/tables"
oz_b <- rd(OZ, "brier_bootstrap_pairs_200-200.csv")
oz_t <- rd(OZ, "twcrps_bootstrap_pairs_200-200.csv")
oz_c <- rd(OZ, "crps_bootstrap_pairs_200-200.csv")
oz_ar2 <- function(df, lvl = NULL) {
  if (is.null(df)) return(NULL)
  r <- df[startsWith(trimws(df$pair), "AR(2)"), ]
  if (!is.null(lvl)) r <- r[abs(r$level - lvl) < 1e-6, ]
  r
}
sim_b <- rd("simstudy/output/results/ar2_paired_tests.csv")
sim_t <- rd("simstudy/output/results/ar2_twcrps_paired.csv")
sim_c <- rd("simstudy/output/results/ar2_crps_paired.csv")
sim_pick <- function(df, st, con, lvl = NULL) {
  if (is.null(df)) return(NULL)
  # Brier cache labels contrasts with a "(K=..)" suffix; CRPS/twCRPS do not.
  r <- df[df$setting == st & startsWith(trimws(df$contrast), con), ]
  if (!is.null(lvl) && "level" %in% names(r)) r <- r[abs(r$level - lvl) < 1e-6, ]
  r
}
TB <- "time_block_forecast/block1_positive_control/output/tables"
tb_b <- rd(TB, "blk1_paired_ci.csv")
tb_t <- rd(TB, "blk1_paired_ci_twcrps.csv")
tb_c <- rd(TB, "blk1_paired_ci_crps.csv")
tb_pick <- function(df, st, ld, con) {
  if (is.null(df)) return(NULL)
  df[df$setting == st & df$leads == ld & df$contrast == con, ]
}

emit <- c()
emit_row <- function(arm, con, bc, tc, cc) sprintf("%s & %s & %s & %s & %s \\\\", arm, con, bc, tc, cc)

# Ozone (interpolation): Brier uses boot_p; representative level 0.95
emit <- c(emit, "\\multicolumn{5}{@{}l}{\\emph{Ozone --- interpolation}}\\\\",
  emit_row("Ozone", "AR(2)$-$AR(1)",
    cell(oz_ar2(oz_b, 0.95), "boot_p"), cell(oz_ar2(oz_t), "boot_p"), cell(oz_ar2(oz_c), "boot_p")))

# Simulation (interpolation): Wilcoxon one-sided; representative K=5 strong (setting 11)
emit <- c(emit, "\\addlinespace", "\\multicolumn{5}{@{}l}{\\emph{Simulation spatial hold-out --- interpolation}}\\\\",
  emit_row("Sim K{=}5 strong", "AR(2)$-$AR(1)",
    cell(sim_pick(sim_b, 11, "AR(2) vs AR(1)", 0.95), "wilcox_p_1sided"),
    cell(sim_pick(sim_t, 11, "AR(2) vs AR(1)"), "wilcox_p_1sided"),
    cell(sim_pick(sim_c, 11, "AR(2) vs AR(1)"), "wilcox_p_1sided")))

# Time-block (extrapolation): Wilcoxon one-sided; near-unit-root, leads 1-5
emit <- c(emit, "\\addlinespace", "\\multicolumn{5}{@{}l}{\\emph{Time-block near-unit-root, leads 1--5 --- extrapolation}}\\\\",
  emit_row("Time-block", "AR(2)$-$iid",
    cell(tb_pick(tb_b, 5, "1-5", "AR(2) - iid"), "wilcox_p_1sided"),
    cell(tb_pick(tb_t, 5, "1-5", "AR(2) - iid"), "wilcox_p_1sided"),
    cell(tb_pick(tb_c, 5, "1-5", "AR(2) - iid"), "wilcox_p_1sided")),
  emit_row("Time-block", "AR(2)$-$AR(1)",
    cell(tb_pick(tb_b, 5, "1-5", "AR(2) - AR(1)"), "wilcox_p_1sided"),
    cell(tb_pick(tb_t, 5, "1-5", "AR(2) - AR(1)"), "wilcox_p_1sided"),
    cell(tb_pick(tb_c, 5, "1-5", "AR(2) - AR(1)"), "wilcox_p_1sided")))

L <- c(
  "% Auto-generated by make_bulk_tail_table.R -- do not edit by hand.",
  "\\begin{table}[htbp]", "\\centering",
  "\\caption{Bulk-vs-tail across the three arms for the AR(2) contrast. Two",
  "tail-focused scores (single-threshold Brier, tail-band twCRPS) vs the",
  "bulk-dominated plain CRPS; verdict by each row's own test at $\\alpha=0.05$",
  "(ozone: two-sided site-clustered bootstrap $p$; simulation and time-block:",
  "one-sided Wilcoxon $p_W$ over $10$ data sets). A score that disagrees with",
  "the two tail scores flags an effect that lives in the bulk, not the tail.}",
  "\\label{tab:bulk-vs-tail}", "\\small",
  "\\begin{tabular}{@{}ll ccc@{}}", "\\toprule",
  "Arm & Contrast & Brier (tail) & twCRPS (tail) & plain CRPS \\\\", "\\midrule",
  emit, "\\bottomrule", "\\end{tabular}", "\\end{table}")

out <- file.path(.this, "bulk_tail_table_body.tex")
writeLines(L, out); cat("Written:", out, "\n"); cat(readLines(out), sep = "\n")
