# make_crps_table.R
# ---------------------------------------------------------------------------
# Unified CRPS-uncertainty summary across the three experiments, to show that
# CRPS's extra power sharpens the interpolation-vs-extrapolation story:
#   interpolation (ozone, sim spatial hold-out) -> AR(2) no better (ozone: worse)
#   extrapolation (time-block forecast)          -> AR(2) better
#
# Reads:
#   ozone:      US-all-auto/output/us-all-auto/tables/crps_bootstrap_pairs_{200-200,300-100}.csv
#   sim:        simstudy/output/results/ar2_crps_paired.csv                [optional]
#   time-block: block1_positive_control/output/tables/blk1_paired_ci_crps.csv
# Writes: crps_table_body.tex
# ---------------------------------------------------------------------------

.this <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "."
})
root <- normalizePath(file.path(.this, "../../../code/analysis"), winslash = "/", mustWork = FALSE)
rd <- function(...) { f <- file.path(root, ...); if (file.exists(f)) read.csv(f, stringsAsFactors = FALSE) else NULL }

oz2 <- rd("ozone/US-all-auto/output/us-all-auto/tables/crps_bootstrap_pairs_200-200.csv")
oz3 <- rd("ozone/US-all-auto/output/us-all-auto/tables/crps_bootstrap_pairs_300-100.csv")
sim <- rd("simstudy/output/results/ar2_crps_paired.csv")
tb  <- rd("time_block_forecast/block1_positive_control/output/tables/blk1_paired_ci_crps.csv")

# emit one table row: label, Delta[CI], p, reading (sig by CI excluding 0)
g <- function(x) formatC(x, format = "fg", digits = 2, flag = "+")  # 2 sig figs, no e-notation
row <- function(arm, lab, Delta, lo, hi, p, punit = "p") {
  sig <- p < 0.05                                   # verdict by the row's own test
  read <- if (!sig) "ns" else if (Delta < 0) "\\textbf{better}" else "\\textbf{worse}"
  sprintf("%s & %s & $%s$ {\\scriptsize $[%s,%s]$} & $%s{=}%.3f$ & %s \\\\",
          arm, lab, g(Delta), g(lo), g(hi), punit, p, read)
}

L <- c(
  "% Auto-generated by make_crps_table.R -- do not edit by hand.",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{CRPS-difference uncertainty across the three arms (whole-",
  "distribution proper score; $\\Delta = \\mathrm{CRPS}_{\\text{first}} -",
  "\\mathrm{CRPS}_{\\text{second}}$, negative favours the temporal/extension",
  "model). Ozone uses a $95\\%$ site-clustered bootstrap CI ($p$ two-sided);",
  "simulation and time-block use a $95\\%$ paired-$t$ CI over the $10$ data sets",
  "($p_W$ one-sided Wilcoxon, H$_1$: temporal better). The reading follows each",
  "row's own test at $\\alpha=0.05$; the two-sided time-block CIs graze $0$ even",
  "where the one-sided $p_W$ is significant. CRPS reveals what $q_{95}$ Brier could not:",
  "AR(2) is (mildly) \\emph{worse} for real-data interpolation yet \\emph{better}",
  "for time-block extrapolation.}",
  "\\label{tab:crps-uncertainty}",
  "\\small",
  "\\begin{tabular}{@{}llccc@{}}",
  "\\toprule",
  "Arm & Contrast & $\\Delta$ CRPS [95\\% CI] & $p$ & reading \\\\",
  "\\midrule"
)

# ---- ozone (interpolation) ----
oz_row <- function(df, split, pat, lab) {
  r <- df[grepl(pat, df$pair), ]; if (nrow(r) == 0) return(NULL)
  row(sprintf("Ozone %s", split), lab, r$Delta, r$CI_lo, r$CI_hi, r$boot_p)
}
L <- c(L, "\\multicolumn{5}{@{}l}{\\emph{Interpolation --- spatial hold-out}}\\\\")
if (!is.null(oz2)) {
  L <- c(L, oz_row(oz2, "200/200", "^AR\\(2\\)", "AR(2) $-$ AR(1)"))
  L <- c(L, oz_row(oz2, "200/200", "^MRTS",       "MRTS $-$ none"))
}
if (!is.null(oz3)) L <- c(L, oz_row(oz3, "300/100", "^AR\\(2\\)", "AR(2) $-$ AR(1)"))

# ---- sim spatial hold-out (interpolation) : AR(2)-AR(1), pooled reading per setting ----
if (!is.null(sim)) {
  s <- sim[sim$contrast == "AR(2) vs AR(1)", ]
  for (i in seq_len(nrow(s)))
    L <- c(L, row(sprintf("Sim %s", gsub("=", "{=}", s$desc[i])), "AR(2) $-$ AR(1)",
                  s$Delta[i], s$CI_lo[i], s$CI_hi[i], s$wilcox_p_1sided[i], "p_W"))
}

# ---- time-block (extrapolation) : near-unit-root headline ----
if (!is.null(tb)) {
  L <- c(L, "\\addlinespace", "\\multicolumn{5}{@{}l}{\\emph{Extrapolation --- time-block forecast}}\\\\")
  pick <- tb[tb$setting == 5 & tb$leads == "1-5", ]
  for (con in c("AR(2) - iid", "AR(2) - AR(1)")) {
    r <- pick[pick$contrast == con, ]
    if (nrow(r)) L <- c(L, row("Near-unit-root (1--5)",
                               gsub("-", "$-$", con), r$Delta, r$CI_lo, r$CI_hi,
                               r$wilcox_p_1sided, "p_W"))
  }
}

L <- c(L, "\\bottomrule", "\\end{tabular}", "\\end{table}")
out <- file.path(.this, "crps_table_body.tex")
writeLines(L, out); cat("Written:", out, "\n"); cat(readLines(out), sep = "\n")
