# make_spectrum_table.R
# ---------------------------------------------------------------------------
# The Brier -> twCRPS -> CRPS "spectrum" for the ozone AR(2) vs AR(1) contrast.
# All three are the same integrand (F(z)-1{y<=z})^2 read at different widths:
#   single-threshold Brier(q0.95)  = one point of the integrand
#   tail-band twCRPS [q0.90,q0.995] = integral over the tail band
#   plain CRPS                      = integral over the whole line (bulk-dominated)
# Shows that CRPS's "AR(2) worse" is a BULK artifact: it vanishes once the score
# is restricted to the tail (Brier and twCRPS both null, twCRPS with high power).
#
# Reads US-all-auto/output/us-all-auto/tables/:
#   brier_bootstrap_pairs_<split>.csv, twcrps_bootstrap_pairs_<split>.csv,
#   crps_bootstrap_pairs_<split>.csv
# Writes: spectrum_table_body.tex
# ---------------------------------------------------------------------------

.this <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "."
})
td <- normalizePath(file.path(.this,
  "../../../code/analysis/ozone/US-all-auto/output/us-all-auto/tables"),
  winslash = "/", mustWork = FALSE)
rd <- function(f) { p <- file.path(td, f); if (file.exists(p)) read.csv(p, stringsAsFactors = FALSE) else NULL }

g <- function(x) formatC(x, format = "fg", digits = 2, flag = "+")
ar2 <- function(df) df[startsWith(trimws(df$pair), "AR(2)"), ]

row <- function(score, region, Delta, lo, hi, p) {
  sig <- p < 0.05
  read <- if (!sig) "ns" else if (Delta < 0) "\\textbf{better}" else "\\textbf{worse}"
  sprintf("%s & %s & $%s$ {\\scriptsize $[%s,%s]$} & $p{=}%.3f$ & %s \\\\",
          score, region, g(Delta), g(lo), g(hi), p, read)
}

L <- c(
  "% Auto-generated by make_spectrum_table.R -- do not edit by hand.",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Ozone AR(2) vs.\\ AR(1) (skew-$t$, $K{=}7$, $T{=}50$): the same",
  "contrast read by three scores on the Brier$\\to$twCRPS$\\to$CRPS spectrum,",
  "with $95\\%$ site-clustered bootstrap CIs. $\\Delta = \\mathrm{score}_{AR(2)} -",
  "\\mathrm{score}_{AR(1)}$; Brier is dimensionless, twCRPS and CRPS in ppb.",
  "The apparent ``AR(2) worse'' of plain CRPS is a bulk effect: restricting the",
  "integral to the tail band (twCRPS) returns a powerful null, agreeing with",
  "single-threshold Brier.}",
  "\\label{tab:twcrps-spectrum}",
  "\\small",
  "\\begin{tabular}{@{}llccc@{}}",
  "\\toprule",
  "Score & Weights & $\\Delta$ [95\\% CI] & $p$ & reading \\\\",
  "\\midrule"
)
for (split in c("200-200", "300-100")) {
  br <- rd(sprintf("brier_bootstrap_pairs_%s.csv", split))
  tw <- rd(sprintf("twcrps_bootstrap_pairs_%s.csv", split))
  cr <- rd(sprintf("crps_bootstrap_pairs_%s.csv", split))
  L <- c(L, sprintf("\\multicolumn{5}{@{}l}{\\emph{%s split}}\\\\", sub("-", "/", split)))
  if (!is.null(br)) { r <- ar2(br); r <- r[abs(r$level - 0.95) < 1e-6, ]
    if (nrow(r)) L <- c(L, row("Brier $q_{0.95}$", "one threshold", r$Delta, r$CI_lo, r$CI_hi, r$boot_p)) }
  if (!is.null(tw)) { r <- ar2(tw)
    if (nrow(r)) L <- c(L, row("twCRPS", "tail band $[q_{.90},q_{.995}]$", r$Delta, r$CI_lo, r$CI_hi, r$boot_p)) }
  if (!is.null(cr)) { r <- ar2(cr)
    if (nrow(r)) L <- c(L, row("CRPS", "whole line (bulk)", r$Delta, r$CI_lo, r$CI_hi, r$boot_p)) }
  L <- c(L, "\\addlinespace")
}
L <- c(L[-length(L)], "\\bottomrule", "\\end{tabular}", "\\end{table}")
out <- file.path(.this, "spectrum_table_body.tex")
writeLines(L, out); cat("Written:", out, "\n"); cat(readLines(out), sep = "\n")
