# make_audit_tables.R
# ---------------------------------------------------------------------------
# Two LaTeX table bodies for the residual UQ audit (folder 09):
#   mc_table_body.tex  <- ozone MC-error batch-means (mc_error_check.csv)
#   fdr_table_body.tex <- BH/BY correction of all paired p-values (fdr_correction.csv)
# ---------------------------------------------------------------------------

.this <- local({ a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) dirname(normalizePath(sub("^--file=", "", a[1]), winslash = "/", mustWork = FALSE)) else "." })
root <- normalizePath(file.path(.this, "../../../code/analysis"), winslash = "/", mustWork = FALSE)
g2 <- function(x) formatC(x, format = "g", digits = 2)

# ---- MC error table ----
mc <- read.csv(file.path(root, "ozone/US-all-auto/output/us-all-auto/tables/mc_error_check.csv"), stringsAsFactors = FALSE)
sclab <- c(brier = "Brier $q_{.95}$", crps = "plain CRPS", twcrps = "twCRPS (tail)")
mc <- mc[match(c("brier", "twcrps", "crps"), mc$score), ]
Lmc <- c(
  "% Auto-generated by make_audit_tables.R",
  "\\begin{table}[htbp]\\centering",
  "\\caption{Posterior Monte-Carlo error of the paired difference $\\Delta$",
  "(batch-means, $G{=}10$ batches of $500$ draws) against the site-bootstrap CI",
  "half-width, ozone AR(2) vs.\\ AR(1), $200/200$. The ratio is MC noise as a",
  "fraction of evaluation uncertainty. Negligible it is not for plain CRPS.}",
  "\\label{tab:mc-error}\\small",
  "\\begin{tabular}{@{}lcccc@{}}\\toprule",
  "Score & $\\Delta$ & MC s.e.$(\\Delta)$ & boot.\\ CI half-width & ratio \\\\\\midrule")
for (i in seq_len(nrow(mc))) Lmc <- c(Lmc, sprintf("%s & $%s$ & $%s$ & $%s$ & $%.2f$ \\\\",
  sclab[mc$score[i]], g2(mc$Delta[i]), g2(mc$mc_se_Delta[i]), g2(mc$boot_CI_halfwidth[i]), mc$ratio_mc_to_boot[i]))
Lmc <- c(Lmc, "\\bottomrule\\end{tabular}\\end{table}")
writeLines(Lmc, file.path(.this, "mc_table_body.tex"))

# ---- FDR table (the nominally significant cells) ----
fd <- read.csv(file.path(root, "simstudy/output/results/fdr_correction.csv"), stringsAsFactors = FALSE)
m <- nrow(fd); nsig <- sum(fd$raw_p < 0.05); nbh <- sum(fd$p_BH < 0.05)
sig <- fd[fd$raw_p < 0.05, ]; sig <- sig[order(sig$raw_p), ]
short <- function(s) { s <- gsub("\\|.*$", "", s); s <- gsub("_", "\\\\_", trimws(s)); s }
Lf <- c(
  "% Auto-generated by make_audit_tables.R",
  "\\begin{table}[htbp]\\centering",
  sprintf(paste0("\\caption{Benjamini--Hochberg (BH) and Benjamini--Yekutieli (BY) ",
    "FDR correction over the whole family of $m=%d$ paired comparisons. ",
    "%d are nominally significant (raw $p<0.05$); \\textbf{%d survive} either ",
    "correction. The nominally significant cells are shown; all are plain-CRPS ",
    "or the sparsest-level Brier, and none clears FDR.}"), m, nsig, nbh),
  "\\label{tab:fdr}\\small",
  "\\begin{tabular}{@{}llccc@{}}\\toprule",
  "Arm & Comparison & raw $p$ & $p_{\\mathrm{BH}}$ & $p_{\\mathrm{BY}}$ \\\\\\midrule")
for (i in seq_len(nrow(sig))) Lf <- c(Lf, sprintf("%s & %s (%s) & $%.3f$ & $%.3f$ & $%.3f$ \\\\",
  sig$arm[i], short(sig$comparison[i]), sig$score[i], sig$raw_p[i], sig$p_BH[i], sig$p_BY[i]))
Lf <- c(Lf, "\\bottomrule\\end{tabular}\\end{table}")
writeLines(Lf, file.path(.this, "fdr_table_body.tex"))

cat("Written mc_table_body.tex and fdr_table_body.tex\n")
cat(sprintf("FDR: m=%d, nominal=%d, survive BH=%d\n", m, nsig, nbh))
